services:
  postgres:
    container_name: nestjs_template_postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_template
